### ISSUE TITLE
Allow Live Flag

### ISSUE THREAD

**Issue by tomgreenhill** [davidwarrington/theme-packer#38]
Theme Packer doesn't seem to to honour the `--allow-live` flag.

Theme Packer version: 1.0.0-beta.3
Node version: 14.6.1

Running `yarn watch:live` aka `theme-packer watch --allow-live`

Please let me know if you require more info!

**Comment by davidwarrington** [comment]
Thanks for flagging, I'll look into it. It's not a feature I've thought to test because working directly on a live theme has never been a part of my workflow, but I know that there are plenty of people who do work that way.

I would advise that you don't run the `watch` command on a published theme though, unless the store you're working on isn't live. CSS and JS are served locally in development mode for the sake of speed, as opposed to being uploaded to Shopify servers, so developing on a live theme will break the site for visitors

**Comment by tomgreenhill** [comment]
Thanks for the reply, ha, yeah fully realise it's a pretty edge case scenario! I totally hear you, not usually in mine either, only reason I noticed is because I'm working on new features/templates that are only present in the development theme, so have the theme set to live and as the store is paused isn't an issue.

Otherwise you're left having to create a new template on the 'live' theme or switching logic in the 'current' template in your dev theme to be able to see those changes on your dev/local theme, ah the joys! 

Coupled with the delete issue I'm just publishing 'live' theme, (re)watch, publish 'dev' theme to live. Not the worst work around! 

Anyway, thanks for putting it out there, great tool alongside your other releases!

**Comment by davidwarrington** [comment]
@tomgreenhill Sorry it's taken 2 weeks to address this. I've been really busy with various things and I've been in two minds as to how I'd want to approach this feature. On the one hand I'd considered passing any flags prefixed with `shopify` to ThemeKit, such as `--shopify-allow-live`. That way it would essentially be futureproof, but adding that prefixed could get annoying. After taking a look at the Theme Kit docs though, it seems I may have been worrying a little too much. I've opened a PR to support passing all of the valid command flags to the `watch` and `deploy` commands, but haven't tested it yet. Hopefully I'll have updated the package later this week.

**Comment by tomgreenhill** [comment]
No need to apologise dude, I'm sure you've got more important things to attend to too! Thanks for the response, much appreciated and look forward to seeing the outcome!

**Comment by davidwarrington** [comment]
@tomgreenhill The latest version should now support flags for the `watch` and `deploy` commands.

I did actually realise earlier today that you can enable some flags with env keys. For example I enabled the no delete flag with `SHOPIFY_NO_DELETE=''` in my `.env` file. But dotenv keeps `true` and `false` as strings, so I figured that's not a great compromise.

**Comment by tomgreenhill** [comment]
Ahh yeah not ideal. That's awesome, confirmed my end thanks again!
